[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
garde.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
tokio.workspace = true
libsql.workspace = true

<<<<<<< HEAD
runtime = { path = "../runtime" }
=======
[dev-dependencies]
tokio = { version = "1", features = ["macros", "time", "test-util"] }
>>>>>>> adc41d2 (test: database integration tests)
